# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  idea.service:
    class: AppBundle\Service\IdeaService
    arguments:
      - @doctrine.orm.entity_manager
      - @security.token_storage
      
  link.service:
    class: AppBundle\Service\LinkService
    arguments:
      - @doctrine.orm.entity_manager

  idea.create.form:
    class: AppBundle\Form\Type\Idea

  idea.create.form.handler:
    class: AppBundle\Form\Handler\Idea
    arguments:
      - @form.factory
      - @idea.create.form
      - @idea.service
      - @link.service
      - @security.token_storage
