idea_list:
    path:      /idea/list
    defaults:  { _controller: AppBundle:Idea:list }

idea_view:
    path:      /idea/{id}
    defaults:  { _controller: AppBundle:Idea:view }

idea_comment:
    path:       /idea/{id}/comment
    defaults:  { _controller: AppBundle:Idea:createComment }
    requirements:
        methods: "POST"
